### ISSUE TITLE
Connection aborted when using the adapter with a local DB

### ISSUE THREAD

**Issue by mxli417** [arangoml/networkx-adapter#18]
Dear all, 

after introducing myself to the Colab notebooks for the networkx-adapter & Arango DB, as well as other learning
resources, I wanted to give the connector a shot myself. As I have a Arango DB instance running locally, I thought 
it would be easily possible to replicate the Colab notebooks "at home". However, even though the connection to 
my local data base, the creation of collections & the restoring of for example the fraud data set works seamlessly,
the "create_networkx_graph" function does not work. It rather raises a series of exceptions which I append below.
The main issue apparently lies in the connection to the database - which definitely exists. As I would like to use
Arango - DB for some learning experiments and ML, I'd be happy if you could provide me some feedback on the
issue. If I have overlooked something, please let me know.

Best, 
Max

Code snippet I tried to execute:
> g = ma.create_networkx_graph(graph_name = "FraudDetection", graph_attributes=fraud_detection_attributes)

Error this produced:
> Traceback (most recent call last):
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
>     chunked=chunked,
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
>     self._validate_conn(conn)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
>     conn.connect()
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\connection.py", line 421, in connect
>     tls_in_tls=tls_in_tls,
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
>     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock)
>   File "C:\Users\mxmd\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 423, in wrap_socket
>     session=session
>   File "C:\Users\mxmd\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 870, in _create
>     self.do_handshake()
>   File "C:\Users\mxmd\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1139, in do_handshake
>     self._sslobj.do_handshake()
> OSError: [Errno 0] Error
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\requests\adapters.py", line 449, in send
>     timeout=timeout
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\util\retry.py", line 532, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
>     raise value.with_traceback(tb)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
>     chunked=chunked,
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
>     self._validate_conn(conn)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
>     conn.connect()
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\connection.py", line 421, in connect
>     tls_in_tls=tls_in_tls,
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
>     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock)
>   File "C:\Users\mxmd\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 423, in wrap_socket
>     session=session
>   File "C:\Users\mxmd\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 870, in _create
>     self.do_handshake()
>   File "C:\Users\mxmd\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1139, in do_handshake
>     self._sslobj.do_handshake()
> urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\basics_w_arangodb.py", line 134, in <module>
>     graph_attributes = fraud_detection_attributes)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\adbnx_adapter\arangoDB_networkx_adapter.py", line 80, in create_networkx_graph
>     cursor = self.db.aql.execute(query)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\arango\aql.py", line 403, in execute
>     return self._execute(request, response_handler)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\arango\api.py", line 74, in _execute
>     return self._executor.execute(request, response_handler)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\arango\executor.py", line 64, in execute
>     resp = self._conn.send_request(request)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\arango\connection.py", line 237, in send_request
>     auth=self._auth,
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\arango\http.py", line 131, in send_request
>     timeout=self.REQUEST_TIMEOUT,
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\requests\sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\requests\sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "c:\Users\mxmd\Desktop\Projects\graph_learning_w_arangodb\avenv\lib\site-packages\requests\adapters.py", line 498, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

**Comment by cw00dw0rd** [comment]
Is it possible to share the notebook? I would be happy to test it locally, as what you have described so far should work.

**Comment by aMahanna** [comment]
Hi @mxli417, the `networkx-adapter` has undergone some heavy refactoring since you posted this. Your issue may have already been resolved, so please check again and let me know if you can still reproduce this error.

Otherwise I can close the discussion
