### ISSUE TITLE
Feature request:  import of graphs from networkx

### ISSUE THREAD

**Issue by MikeB2019x** [arangoml/networkx-adapter#19]
Situation:  Currently the adapter allows networkx to make use of graphs in arangodb.

Challenge:  I  analyze and compare networks, constantly ingesting new ones and comparing them to existing networks.  All my graphs work is done with networkx and pandas.  I want to make interesting networks available for non-analysts to explore through arangodb.

Feature:  make it possible for networkx graphs to be transferred to arangodb.  A possible solution might be the ability to use the [GraphML](http://graphml.graphdrawing.org/) standard as an intermediate step?

**Comment by aMahanna** [comment]
Hey @MikeB2019x 

As of #25, this has been implemented with the help of a user-defined controller class. You can check it out in our official `v1.0.1` ArangoDB-NetworkX Adapter Notebook Tutorial:

https://colab.research.google.com/github/arangoml/networkx-adapter/blob/master/examples/ArangoDB_NetworkxAdapter.ipynb#scrollTo=bvzJXSHHTi3v

**Comment by aMahanna** [comment]
Closing since it has been resolved
