### ISSUE TITLE
Migrate non-adbnx-adapter material to other repositories

### ISSUE THREAD

**Issue by aMahanna** [arangoml/networkx-adapter#33]
In order for us to properly take advantage of https://github.com/arangoml/networkx-adapter/issues/29, we should consider migrating material that does not directly relate to the `adbnx-adapter` package.

More specifically:
* `examples/**/*`
* `bipartite_clustering.pdf`

This would allow us to "flesh-out" the `networkx-adapter/adbnx_adapter` directory to the root of the repo, allowing us to avoid things like [this](https://github.com/arangoml/networkx-adapter/blob/1.0.1/.github/workflows/build.yml#L6-L8)

We would need to figure out an ideal destination for this material. Perhaps [arangodb/interactive_tutorials](https://github.com/arangodb/interactive_tutorials) ?

**Comment by rajivsam** [comment]
@aMahanna , I am ok with even deleting bipartite_clustering.pdf

**Comment by cw00dw0rd** [comment]
Discussed this with Anthony and agreed to keep the notebook and relevant documents in the repo if we can ignore certain files using GitHub Actions.
