### ISSUE TITLE
Rename adbnx_adapter method names

### ISSUE THREAD

**Issue by aMahanna** [arangoml/networkx-adapter#34]
I'd like to rename some of the methods to keep things consistent with potentially upcoming adapters 👀 :
* `create_networkx_graph()` becomes `adb_to_nx()`
* `create_networkx_graph_from_arangodb_collections()` becomes `adb_to_nx_from_collections()`
* `create_networkx_graph_from_arangodb_graph()` becomes `adb_to_nx_from_graph()`
* `create_arangodb_graph()` becomes `nx_to_adb()`

Happy to take feedback on this 🚀

**Comment by rajivsam** [comment]
SGTM and LGTM

**Comment by geenen124** [comment]
@aMahanna I'd advocate for a bit more verbosity so that the method names are a bit clearer at first glance?
e.g. `adb_to_nx()` could become `arangodb_to_networkx()`, and `adb_to_nx_from_collections()` could become `arangodb_to_networkx_from_collections()` etc.

**Comment by aMahanna** [comment]
Ah sounds good! Will update 👍

**Comment by aMahanna** [comment]
To avoid an extra release, which I would argue is unnecessary here, I've changed the destination of #35 to point to `feature/batch-insertion`. 

Merge process will go as follows:
1. #35 merges into `feature/batch-insertion` (where #30 is active)
2. #30 merges into `master`

Here is the confirmed list of changes I will be making:

Public methods (increased verbosity):
* `create_networkx_graph()` becomes `arangodb_to_networkx()`
* `create_networkx_graph_from_arangodb_collections()` becomes `arangodb_collections_to_networkx()`
* `create_networkx_graph_from_arangodb_graph()` becomes `arangodb_graph_to_networkx()`
* `create_arangodb_graph()` becomes `networkx_to_arangodb()`

Protected methods (increased verbosity):
* `_prepare_adb_vertex()` becomes `_prepare_arangodb_vertex()`
* `_prepare_adb_edge()` becomes `_prepare_arangodb_edge()`
* `_identify_nx_node()` becomes `_identify_networkx_node()`
* `_identify_nx_edge()` becomes `_identify_networkx_edge()`
* `_keyify_nx_node()` becomes `_keyify_networkx_node()`
* `_keyify_nx_edge()` becomes `_keyify_networkx_edge()`

Private methods (reduced verbosity, given that the package user will not be interacting with this logic)
* `__fetch_arangodb_docs()` becomes `__fetch_adb_docs()`
* `__insert_arangodb_vertex()` becomes `__insert_adb_vertex()` 
* `__insert_arangodb_edge()` becomes `__insert_adb_edge()` 
* `__insert_networkx_node()` becomes `__insert_nx_node()`
* `__insert_networkx_edge()` becomes `__insert_nx_edge()`
