### ISSUE TITLE
Reformat package & file names

### ISSUE THREAD

**Issue by aMahanna** [arangoml/networkx-adapter#46]
I'd like to introduce a consistent project structure & file/class name standard for future ArangoDB Adapters. The PyPi package name standard will still remain as `adb<destination>_adapter`, where `<destination>` is the graph service target. For example, we would have:
1. `adbnx_adapter` for ArangoDB / NetworkX
2. `adbdgl_adapter` for ArangoDB / DGL
3. `adbpyg_adapter` for ArangoDB / Pytorch Geometric

In theory, these changes should establish the standard of how ArangoDB Adapters are made. So if we accept this for NetworkX, we are accepting this for everything else. If this passes, I will also be making the relevant changes for https://github.com/arangoml/dgl-adapter

### Before
```
.
├── CHANGELOG.md
├── LICENSE
├── README.md
├── VERSION
├── adbnx_adapter
│   ├── adbnx_adapter
│   │   ├── __init__.py
│   │   ├── abc.py
│   │   ├── adbnx_adapter.py
│   │   └── adbnx_controller.py
│   └── tests
│       ├── arangorestore
│       ├── conftest.py
│       └── test_adbnx_adapter.py
├── examples (...)
└── scripts (...)
```

### After
```
.
├── CHANGELOG.md
├── LICENSE
├── README.md
├── VERSION
├── adbnx
│   ├── adbnx
│   │   ├── __init__.py
│   │   ├── abc.py
│   │   ├── adapter.py
│   │   └── controller.py
│   └── tests
│       ├── assets
│       │   └── arangorestore
│       ├── conftest.py
│       └── test_adapter.py
├── examples (...)
└── scripts (...)
```

## Class Names
* `abc.ADBNX_Adapter` becomes `abc.Abstract_ADBNX_Adapter`
* `abc.ADBNX_Controller` becomes `abc.Abstract_ADBNX_Controller`
* `adbnx_adapter.ArangoDB_Networkx_Adapter` becomes `adapter.ADBNX_Adapter`
* `adbnx_controller.Base_ADBNX_Controller` becomes `controller.ADBNX_Controller`

**Comment by aMahanna** [comment]
@geenen124 @cw00dw0rd @rajivsam 

Hey guys,

I am looking for feedback on this, before I start to address it. I'm interested to see what you guys think, and as always I am more than happy to adjust

**Comment by rajivsam** [comment]
@aMahanna , LGTM. I am ok with it.

**Comment by geenen124** [comment]
@aMahanna I would be in favor of keeping `adbnx_adapter` as the module name instead of `adbnx` to keep it 1:1 with the name of the module that we're publishing to pypi (that way the qn of which module/folder is going to end as the package root is also answered by the folder structure). 

The class name changes look good to me 👍

**Comment by aMahanna** [comment]
> @aMahanna I would be in favor of keeping `adbnx_adapter` as the module name instead of `adbnx` to keep it 1:1 with the name of the module that we're publishing to pypi (that way the qn of which module/folder is going to end as the package root is also answered by the folder structure). 
> 
> 
> 
> The class name changes look good to me 👍 

Sounds good! will do
