### ISSUE TITLE
Expose ArangoClient & StandardDatabase from adapter to provide driver client accessibility

### ISSUE THREAD

**Issue by aMahanna** [arangoml/networkx-adapter#70]
## Current Functionality

```python
from adbnx_adapter.adapter import ADBNX_Adapter # pip install adbnx-adapter

con = {
    "hostname": "localhost",
    "protocol": "http",
    "port": 8529,
    "username": "root",
    "password": "rootpassword",
    "dbName": "_system",
}

adbnx_adapter = ADBNX_Adapter(con) # no direct access to ArangoClient or StandardDatabase constructor 
```

## Proposed Functionality
```python
from arango import ArangoClient # pip install python-arango
from adbnx_adapter.adapter import ADBNX_Adapter # pip install adbnx-adapter

# full access to ArangoClient and StandardDatabase constructor, implying that the user can instantiate the client however they want (i.e custom HTTP client, serializer, deserializer, etc..) 
db = ArangoClient(hosts="http://localhost:8529").db("_system", username="root", password="rootpassword") 

adbnx_adapter = ADBNX_Adapter(db)
```

Would this not make more sense?

**Comment by cw00dw0rd** [comment]
What would you see as the main benefit of this approach?

I think this method would be good but I also see the convenience of the other way. Especially for those that won't be doing any other Arango operation aside from pulling data -> networkx activity -> pushing data back. 

I would also suggest some way to access the database connection of the adapter such as #65 which was a requested feature.

Could we have it be either a connection string or a database object for convenience and backward compatibility? Would having both complicate things?

**Comment by aMahanna** [comment]
> What would you see as the main benefit of this approach?

I think full access to your DB client is always good news, you would now be able to access all the previously hidden `ArangoClient` parameters such as: `host_resolver`, `resolver_max_tries`, `http_client`, and (soon to be) `verify_override`.

> I think this method would be good but I also see the convenience of the other way. Especially for those that won't be doing any other Arango operation aside from pulling data -> networkx activity -> pushing data back.

True, this would be the small convenience loss we'd have to accept. But I think the main benefit outweighs it

> I would also suggest some way to access the database connection of the adapter such as https://github.com/arangoml/networkx-adapter/pull/65 which was a requested feature.

Absolutely, I have this change made in https://github.com/arangoml/dgl-adapter/pull/12 and plan on doing the same for this adapter, and future ones 👀 

> Could we have it be either a connection string or a database object for convenience and backward compatibility? Would having both complicate things?

Unfortunately unlike Java, Python's ability to support multiple constructors based on parameter type is limited. We'd have to rely on `isinstance()` - which is not bad at all - but it would not help in keeping the constructor cleanly implemented.

**Comment by aMahanna** [comment]
Like you mentioned this isn't backwards compatible

Given our plan regarding #71, we are expecting to have a major release soon anyway, so I think this would fit nicely in a `4.0.0` release where #69, #70, and #71 are addressed

**Comment by cw00dw0rd** [comment]
Sounds good to me!
