### ISSUE TITLE
Consider a 'Verbose' option for adapter functionality

### ISSUE THREAD

**Issue by aMahanna** [arangoml/networkx-adapter#72]
## Current state:
* Adapter functionality is performed silently, with minimal logs:
    * Log a "success" message before connecting to an ArangoDB endpoint
    * Log a "success" message at the end of an API call

## Proposed feature:
* Provide a `verbose` parameter option to all adapter API functionality, such that the package user is aware of all step-by-step operations performed:
    * ~~Log on attribute validation~~
    * Log on `__fetch_adb_docs` calls
    * ~~Log on Controller calls~~ (will leave this up to the user to configure if desired)
    * Log on NetworkX graph creation
    * Log on ArangoDB collection creation
    * Log on document insertions
    * etc.

## Sample

```py
adbnx_adapter.set_verbose(True)
nx_graph = adbnx_adapter.arangodb_graph_to_networkx("fraud-detection")
```

Not sure yet if this should be implemented, so will leave it with a `question` label for now

**Comment by cw00dw0rd** [comment]
I see, that would be cool, assuming it's low effort. What would the main benefit be?

**Comment by aMahanna** [comment]
I think it could be useful for debugging purposes. 

Should a user ever end up with an unsuccessful ArangoDB --> NetworkX or NetworkX --> ArangoDB attempt, they could re-run their attempt to understand why it failed, and provide logs to see if the failure is potentially a bug
